config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "groups#index"
  
  resources :group_types, only: [:index, :show]
  resources :groups do
    resources :posts do
      resources :comments do
        resources :comments, only: [:create, :update, :destroy]
      end
    end
    resources :group_memberships, only: [:create, :destroy]
  end

  match '*unmatched', to: 'application#route_not_found', via: :all
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :posts, dependent: :destroy
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships
  has_many :admins,
    -> { where('group_memberships.role': :admin) },
    through: :group_memberships,
    source: :user

  validates :title, presence: true, allow_blank: false
  validates :user_id, presence: true

  def total_members
    users.count
  end

  def total_posts
    posts.count
  end

  def ordered_posts
    posts.order(created_at: :desc)
  end

  def last_activity
    if posts&.last&.created_at
      (Time.current - posts.last.created_at).to_i
    else
      (Time.current - created_at).to_i
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update, :destroy]

  def index
    @groups = Group.includes(:posts).order(created_at: :desc)
  end

  def show
    @group = Group.includes(posts: [user: :avatar_attachment]).find(params[:id])
    authorize @group
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    authorize @group

    respond_to do |format|
      if @group.save
        create_group_membership
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('groups', partial: 'groups/group', locals: {group: @group}) }
        format.html { redirect_to groups_path(all: true), notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @group

    respond_to do |format|
      if @group.update(group_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@group, partial: 'groups/group', locals: {group: @group}) }
        format.html { redirect_to groups_path, notice: 'Group was successfully updated.' }
      end
    end
  end

  def destroy
    authorize @group

    @group.destroy
  end

  def member
    @groups = current_user.groups

    respond_to do |format|
      format.html { render template: 'groups/index' }
    end
  end

  def created_by_me
    @groups = current_user.groups.where(user_id: current_user.id)

    respond_to do |format|
      format.html { render template: 'groups/index' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:title)
  end

  def create_group_membership
    @membership = GroupMembership.new(group_id: @group.id, user_id: current_user.id, role: :admin)
    @membership.save!
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <div id="defaultModal" tabindex="-1" aria-hidden="true" class="flex justify-center overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
      <div class="relative p-4 w-full max-w-2xl h-full md:h-auto mt-24">
          <!-- Modal content -->
          <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
              <!-- Modal header -->
              <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                  <h3 id="form-title" class="text-xl font-semibold text-gray-900 dark:text-white ml-6 mt-1.5">
                      <%= title %>
                  </h3>
                  <button type="button" data-action="turbo-modal#hideModal" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal">
                      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                      <span class="sr-only">Close modal</span>
                  </button>
              </div>
              <!-- Modal body -->
              <div class="p-6 space-y-6">
              <div>
                <% if group.errors.any? %>
                  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
                    <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

                    <ul>
                      <% group.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <div>
                <div class="flex my-5">
                  <div class="w-full ml-6 basis-2/4">
                    <h3 class="text-m font-semibold text-gray-500 dark:text-white">
                      Group Name
                  </h3>
                  <p class=" mt-2 text-sm text-gray-500 dark:text-white"> People will see this name before joing your group </p>
                  </div>
                  <%= form.text_field :title, autofocus: true, placeholder: "Title of your group",required: true, class: "data relative block w-full appearance-none rounded-none rounded-t-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm" %>
                </div>
              </div>
              <!-- Modal footer -->
              <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
                  <%= form.submit data: {action: "turbo:submit-end->turbo-modal#submitEnd"}, class: "ml-6 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
              </div>
          </div>
      </div>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="flex flex-row gap-2 ml-6 mt-6 shadow-md">
    <div class="flex flex-col bg-white shadow p-2 border-t-4 border-green-600 rounded basis-3/5 max-w-sm w-full lg:max-w-full lg:flex w-9/12" style="overflow:overlay"">
        <header class="p-2 border-b flex"> 
            <div class="flex flex-col max-w-sm w-full lg:max-w-full lg:flex w-9/12">
                <h1 class="text-lg font-mono text-green-600 max-w-sm w-full lg:max-w-full lg:flexw-9/12" style="overflow-wrap: break-word;""> <%=group.title %></h1>
            </div>
        </header>
        <div class="flex flex-wrap p-2 w-full gap-4">
            <div class="flex flex-col w-full">
                <h1 class="text-lg">Last activity 0 minutes ago</h1>
            </div>

            <div class="flex flex-col">
                <h1 class="text-md"><%= group.total_members %> Members</h1>
            </div>

            <div class="flex flex-col">
                <h1 class="text-md font-thin"> <%= group.total_posts %> Posts</h1>
            </div>
            <%if @current_user.member? group%>
                <div class="flex flex-col">
                    <h1><%=link_to "View group", group_path(group.id), class: "view-group text-gray-600 block hover:text-green-300 focus:outline-none" %></h1>
                </div>
            <%end%>
        </div>
    </div>
    <div class='flex items-center justify-center mr-10 basis-2/5'>
            <div class='flex bg-white border-solid rounded-3xl border-green-600 px-8 py-4 mb-4 w-28 mx-16' style="
                border: solid;
                border-color: green;"
            >
                <div class="ml-2">
                    <i class="fa fa-check"></i>
                </div>
            </div>
        </div>
</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Edit group</h1>
  <%= render TurboModalComponent.new(title: "New Group!") do %>
    <%= render "form", group: @group,title: "Edit Group", button: "Save" %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="w-full">
  <div class="flex flex-col justify-between items-center items-baseline">
    <div class="ml-6">
    <h1 class="font-bold text-4xl">Groups</h1>
    </div>
    <div class="flex justify-between w-full">
    <div class="ml-6 mt-6">
      <nav class="flex flex-row">
          <%=link_to groups_path(all: true), class: params[:all] ? "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none text-blue-500 border-b-2 font-medium border-blue-500" : "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none font-medium" do %>
              All Groups
          <% end %>
          <%= link_to group_type_path(id: 0, created: true), class: params[:created] ? "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none text-blue-500 border-b-2 font-medium border-blue-500" : "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none" do %>
              Created by me
          <% end %>
          <%= link_to group_types_path(member: true), class:  params[:member] ? "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none text-blue-500 border-b-2 font-medium border-blue-500" : "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none" do%>
              Where I am a member
          <% end %>
      </nav>
    </div>
    <%= link_to '+ Create a new group', new_group_path,data: { turbo_frame: 'modal' }, class: "mr-6 self-end rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  </div>
    <div id="groups" class="min-w-full" style="margin-bottom: 50px">
      <%if @groups.present?%>
        <%= render(GroupComponent.with_collection(@groups, user: current_user)) %>
      <%else%>
        <%= render(EmptyBoxComponent.new(title: "No groups to show"))%>
      <%end%>
    </div>

</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>
  <%= render TurboModalComponent.new(title: "New Group!") do %>
    <%= render "form", group: @group,title: "Create Group", button: "Create" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="flex flex-col margin-bottom: 50px">
  <div class="flex" style="max-height: 450px;">
    <div class="flex flex-col basis-3/5 ml-24" style="margin-left: 100px; overflow: auto">
      <div class="flex">
        <div class="ml-6 ">
          <h1 id="title" class="font-bold text-3xl" style="overflow-wrap: anywhere;"><%= @group.title %></h1>
        </div>
        <% if current_user.admin @group%>
          <div class="mt-2 ml-2">
            <%= link_to edit_group_path(@group.id),data: { turbo_frame: 'modal' } do%>
              <i class="fa-solid fa-gear fa-lg"></i>
            <%end%>
          </div>
        <%end%>
      </div>
      <div>
        <%= render(PostFormComponent.new(group: @group, post: @group.posts.build))%>
      </div>
    </div>
    <div class="flex flex-col basis-2/5 h-full align-center" style="align-items: center;">
      <div class="flex justify-center py-4 px-6 border-b-2 border-green-400 w-2" style="width: fit-content;border-color: rgb(220 252 231);">
        <h1 class="text-3xl">Members</h1>
      </div>
      <%= render(MemberComponent.with_collection(@group.users, group: @group, user: current_user))%>
    </div>
  </div>
  <div class="flex flex-col mt-6">
    <h1 class="font-bold text-3xl" style="margin-left: 130px; margin-top: 20px;">All Posts</h1>
    <%unless @group.posts.empty?%>
      <%= render(PostComponent.with_collection(@group.ordered_posts, show: false, user: current_user))%>
    <%else%>
      <div style="margin-left: 130px; margin-top: 20px;">
        <%= render(EmptyBoxComponent.new(title: "No Posts to show"))%>
      </div>
    <%end%>
  </div>
</div>